# NewsAPI
newsapi.key=81e338badb1f4776b66bf69b245f0407
newsapi.url=https://newsapi.org/v2/top-headlines?category=technology&language=en&pageSize=10&apiKey=

# SQLite database
database.path=news.db

# ActiveMQ broker
broker.url=tcp://localhost:61616
broker.topic=TechNews

# Capture interval (minutes)
capture.interval.minutes=30